openapi: 3.0.0
info:
  title: Library API Mock
  version: 1.0.0
paths:
  /books:
    get:
      summary: Отримати список книг
      responses:
        '200':
          description: Успішна відповідь
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
              example:
                - id: "550e8400-e29b-41d4-a716-446655440000"
                  title: "Clean Code"
                  author: "Robert Martin"
                  year: 2008
    post:
      summary: Створити книгу
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreate'
      responses:
        '201':
          description: Книгу створено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

components:
  schemas:
    Book:
      type: object
      properties:
        id: { type: string, format: uuid }
        title: { type: string }
        author: { type: string }
        year: { type: integer }
    BookCreate:
      type: object
      required: [title, author, year]
      properties:
        title: { type: string }
        author: { type: string }
        year: { type: integer }